title: "Quantingo Apps"
theme: null
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "docs"

  - scope:
      path: "QR-Code-Pro"
    values:
      layout: "app_qrcodepro"
      nav_order: 1

  - scope:
      path: "Barcode-Pro"
    values:
      layout: "app_barcodepro"
      nav_order: 2
