title: "Quantingo Apps"

defaults:
  - scope:
      path: ""
      type: pages

  # Configura o layout para QR Code Pro
  - scope:
      path: "QR-Code-Pro"
      type: pages
    values:
      layout: "app_qrcodepro"
      nav_order: 1

  # Configura o layout para Barcode Pro
  - scope:
      path: "Barcode-Pro"
      type: pages
    values:
      layout: "app_barcodepro"
      nav_order: 2

  # Configura o layout para Numerix
  - scope:
      path: "Numerix"
      type: pages
    values:
      layout: "app_numerix"
      nav_order: 3

  # Configura o layout para Bounce Ball
  - scope:
      path: "Bounce-Ball"
      type: pages
    values:
      layout: "app_bounceball"
      nav_order: 4

  # Configura o layout para Momentum
  - scope:
      path: "Momentum"
      type: pages
    values:
      layout: "app_momentum"
      nav_order: 5
