title: "Quantingo Apps"

theme: null
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

defaults:
  # Ativa a sidebar 'docs' em TODAS as p√°ginas
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "docs"

  # Configura o layout para QR Code Pro
  - scope:
      path: "QR-Code-Pro"
      type: pages
    values:
      layout: "app_qrcodepro"
      nav_order: 1

  # Configura o layout para Barcode Pro
  - scope:
      path: "Barcode-Pro"
      type: pages
    values:
      layout: "app_barcodepro"
      nav_order: 2
